// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using verify.DataLayer.Data;

namespace verify.DataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230803083301_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("verify.DataLayer.Entites.AadhaarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AadhaarNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AadhaarData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AadhaarNumber = "124692735693"
                        },
                        new
                        {
                            Id = 2,
                            AadhaarNumber = "865196029806"
                        },
                        new
                        {
                            Id = 3,
                            AadhaarNumber = "378926190808"
                        },
                        new
                        {
                            Id = 4,
                            AadhaarNumber = "944879507126"
                        },
                        new
                        {
                            Id = 5,
                            AadhaarNumber = "364866624600"
                        });
                });

            modelBuilder.Entity("verify.DataLayer.Entites.PANEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PAN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PANData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PAN = "1343CA3FEC"
                        },
                        new
                        {
                            Id = 2,
                            PAN = "23CECC43EA"
                        },
                        new
                        {
                            Id = 3,
                            PAN = "FECD3D44FD"
                        },
                        new
                        {
                            Id = 4,
                            PAN = "AA4D1C1DAE"
                        },
                        new
                        {
                            Id = 5,
                            PAN = "24EB4AD3D2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
